### ISSUE TITLE
Archive page and change name when permissions do not allow "trashing" (destroy)

### ISSUE THREAD

**Issue by justinTM** [chesshacker/terraform-provider-confluence#9]
I'm using Confluence Cloud, and my administrator has disabled the ability to delete pages. It would be cool, instead of erroring on permissions error for destroy, to change the name to something unique and archive it. Error below:

```shell
Error: 403 Forbidden

DELETE /wiki/rest/api/content/23049824359877234


com.atlassian.confluence.api.service.exceptions.PermissionException: Unable to trash content with id: ContentId{id=234908345987234}
Authorized: false
Valid: true
Successful: false


Error: 400 Bad Request

POST /wiki/rest/api/content


com.atlassian.confluence.api.service.exceptions.BadRequestException: A page with this title already exists: A page already exists with the title MyPageTitle1
Authorized: false
Valid: true
Successful: false

  with confluence_content.panels_by_template,
  on confluence.tf line 131, in resource "confluence_content" "panels_by_template":
 131: resource confluence_content "panels_by_template" {
```

**Comment by justinTM** [comment]
@DrFaust92 if you are willing I would love to tackle this with a little bit of your help. I am pretty well-versed with Terraform at this point and have built a custom ConfluencePage class to try to expand the functionality of this provider plugin; I just don't know Golang

**Comment by DrFaust92** [comment]
I don't think this is right. this is a very specific org limitation and i would not introduce it as a feature.
